apiVersion: networking.k8s.io/v1
kig: ingress
metadata:
  name: demo-ingress
spec:
  rule:
  - host: exemple.com
    http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /paiement
        pathType: Prefix
        backend:
          service:
            name: paiement-service
            port:
              number: 5000
      - path: /verification
        pathType: Prefix
        backend:
          service:
            name: verification-service
            port:
              number: 3000